project:
  type: book
  output-dir : docs

book:
  title: "Modern Polars"
  author: "Kevin Heavey"


chapters:
    - index.qmd
    - education.qmd
    - welcome.qmd

format:
  html:
    theme:
      light: cosmo
    code-fold: false
    css: custom.css
    backgroundcolor: "#F5F5F5"